# Test with these Schemes.
env:
  matrix:
    - SCHEME="ChezScheme"
    - SCHEME="Guile"
    - SCHEME="Sagittarius"

addons:
  apt:
    packages:
      - guile-2.0
      # For Sagittarius
      - libgc-dev
      - zlib1g-dev
      - libffi-dev

language: c

cache: ccache

os:
  - linux

compiler:
  - gcc

before_script:
  - eval "$(./build-scheme.sh $SCHEME)"

script:
  - ./run-tests.sh
