# Test with these Schemes.
env:
  matrix:
    - SCHEME="ChezScheme_master"
    - SCHEME="Guile_preinstalled"
    - SCHEME="Larceny"
    - SCHEME="Racket_6.2"
    - SCHEME="Racket_HEAD"
    - SCHEME="SagittariusScheme"
    - SCHEME="VicareScheme"

matrix:
  allow_failures:
    - env: SCHEME="Larceny"

addons:
  apt:
    packages:
      - guile-2.0
      # For Vicare
      - libgmp-dev
      # Sagittarius
      - libgc-dev
      - zlib1g-dev
      - libffi-dev
      # For Larceny
      - libc6:i386

language: c

cache: ccache

os:
  - linux

compiler:
  - gcc

before_script:
  # Install scheme-ci
  - wget https://github.com/weinholt/scheme-ci/archive/master.zip -O scheme-ci-master.zip
  - unzip scheme-ci-master.zip
  - eval "$(scheme-ci-master/install-scheme.sh $SCHEME)"

script:
  - ./run-tests.sh
