# Test with these Schemes.
env:
  matrix:
    - SCHEME="ChezScheme"
    - SCHEME="Guile"
    - SCHEME="Racket"
    - SCHEME="Sagittarius"
    - SCHEME="Vicare"

addons:
  apt:
    packages:
      - racket
      - guile-2.0
      # For Sagittarius
      - libgc-dev
      - zlib1g-dev
      - libffi-dev
      # For Vicare
      - libgmp-dev

language: c

cache: ccache

os:
  - linux

compiler:
  - gcc

before_script:
  - set -o pipefail && eval "$(./build-scheme.sh $SCHEME)"

script:
  - ./run-tests.sh
